# permissions for end users to view podwatchmen.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podwatchman-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operators
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
  name: podwatchman-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - podwatchmen
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - podwatchmen/status
  verbs:
  - get
